### ISSUE TITLE
can't open smap

### ISSUE THREAD

**Issue by alereyvinn** [JoseRuedaRueda/ScintSuite#22]
Now that I created a new branch from developer, some of the smap give me some problems. Any idea of what happens?

**Comment by JoseRuedaRueda** [comment]
For next time, please follow the template which is linked in the readme. It is impossible to give any help with the null amount of information provided here. You should indicate: the precise error (console output), which line of the suite is giving the issue, which parameters are you using as inputs, steps to reprooduce the issue, etc...
